#spring.profiles.active=test
spring:
  profiles:
#    active: test
    active: dev
#    active: prod

default:
  sender: sinaldasorteweb@gmail.com
  recipient: sinaldasorteweb@gmail.com

# Palavra qualquer que serve como segredo para o JWT
jwt:
  secret: SaintClairTICParaTodos
# Tempo de expiração do token. 60000ms=1min, tempo curto para facilitar os testes, mas o ideal é aumentar o tempo para 24 horas, 1 semana ou mais
#60000*60*24 = 86400000ms = 24 horas
#jwt.expiration=86400000
# 30 dias
  expiration: 2592000000