spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
#debug
  jpa:
    show-sql: false
#mostra as execuções de queries de forma amigável
    properties:
      hibernate:
        format_sql: true  
  
  output:
    ansi:
      enabled: DETECT

sinaldasorte:
  front:
    url: http://localhost:8100/
  ws:
    url: http://localhost:8080/
  www: www.sinaldasorte.com
  email: sinaldasorteweb@gmail.com
  adverbio: Atenciosamente
  responsavel: Ali
  copyright: Copyright Sinal da Sorte 2018
  organizacao: Sant'Clear
  slogan: Aposte com estratégia.
  
organizacao:
  nome: Sant'Clear Soluções
  email: santclearsolucoes@gmail.com
  
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
    br:
      com:
        sinaldasorte: DEBUG
